version: '3.9'
services:
  nestapp:
    container_name: nestapp
    image: christopher96u/nestapp:1.0.0
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - DATABASE_USERNAME=$DATABASE_USERNAME
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - DATABASE_NAME=$DATABASE_NAME
      - DATABASE_PORT=$DATABASE_PORT
      - DATABASE_HOST=db
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    env_file:
      - .env
    environment:
      - POSTGRES_USER:$DATABASE_USERNAME
      - POSTGRES_PASSWORD:$DATABASE_PASSWORD
      - POSTGRES_DB:$DATABASE_NAME
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
